#!/bin/ksh

# ========= /tmp backup program =========== #
# Makes a backup of all the _SBo.tgz files  #
# in /tmp directory, compressing them to    #
# one file and moving it to user's .backups #
# directory.				     #
# ========================================= #
#
# Gabriel Ribeiro 
# thefourthpillar@protonmail.com
#
#

UID="$(id -u)" # User ID number

[ $UID != "0" ] && { print "You need to be root! Exiting..."; sleep 2s; exit 1 ;}

read _bkp?"Name your backup file: "

# Program functions
function _user
{
	read _owner?"Which USER is going to be the owner? "
}

function backup
{
	[ ! -d $HOME/.backups ] && mkdir $HOME/.backups # if .backups is inexistent, create it.
	
	tar cfv $_bkp.tgz /tmp/*_SBo.tgz
	
	if [ $_owner != "root" ]; then 
		[ ! -d /home/$_owner/.backups ] && mkdir -v /home/$_owner/.backups
		mv -v $_bkp.tgz /home/$_owner/.backups
	else
		mv -v $_bkp.tgz $HOME/.backups
	fi

	sleep 1s && { clear; print "Backup done." ;}
}

# Start
_user

while [ ! -d /home/$_owner ]; do # Checks if _owner variable is valid
	print "Non-existent user. Please, try again."
	_user
done

backup
