#!/bin/ksh

batstatus=$(acpi | cut -b '25 26 27')
batcharge=$(acpi | cut -b '22 23 24')


if [ $(acpi | cut -b '12 13 14 15') == "Char" ]; then
	print "$batcharge"
elif [ $(acpi | cut -b '12 13 14 15') == "Full" || "$batcharge" == "100" ]; then
	print "FULL"
else
	print "$batstatus"
fi
